spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/smart_inventory?currentSchema=public&TimeZone=Asia/Kolkata
    username: smartuser
    password: smartpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
