services:
  postgres:
    image: postgres:16
    container_name: smart_inventory_db
    environment:
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpass
      POSTGRES_DB: smart_inventory
      PGTZ: Asia/Kolkata
    ports:
      - "5434:5432"
    command:
      [
        "postgres",
        "-c",
        "hba_file=/etc/postgresql/pg_hba.conf",
        "-c",
        "listen_addresses=*",
      ]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
volumes:
  postgres_data:
